Create the n-dimensional grid:

In [178]:
## import numpy as np

dimensions = 3
side_size = 3
def get_cellular_automata_grid(dimensions, side_size):
    
    grid_shape = [side_size] * dimensions
    grid = np.zeros(grid_shape)
    return grid

def get_neighbour_indices(grid, cell_index):
    # TODO: Von Neumann
    # TODO: check if cell index dims & grid ones match
    grid_shape = grid.shape
    assert(len(grid_shape) == len(cell_index))
    
    neighbours = np.array([cell_index] * len(cell_index))
    print("neighbours: ", neighbours)
    
#     for dimension_index in cell_index:
#         assert(dimension_index < grid_shape[dimension_index])
#         if dimension_index == grid_shape[dimension_index]:
#             current_index = 0
#         else:
#             current_index = dimension_index + 1
      
    for i in range(len(neighbours)):        
        if neighbours[i][i] == grid.shape[i] - 1:
            neighbours[i][i] = 0
        else:
            neighbours[i][i] = neighbours[i][i] + 1
#         print(i, i)
#     index = 0
#     dimension = 0
#     for neighbor in neighbours:
        
#         current_index = neighbours[dimension][index]
        
#         if current_index == grid_shape[dimension] - 1:
#             current_index = 0
#         else:
#             current_index = current_index + 1
        
#         neighbours[dimension][index] = current_index
# #         print("neighbor", neighbor)
#         index = index + 1
#         dimension = dimension + 1
    
        
    return neighbours

grid1 = get_cellular_automata_grid(dimensions, side_size)
cell_index1 = np.array([1, 1, 1])
neighbhour_indices = get_neighbour_indices(grid1, cell_index1)


# Print
print("grid1\n", grid1)
print("cell_index\n", cell_index1)
print("neighbhour_indices\n", neighbhour_indices)
# New grid
grid1_last = grid1.copy()
grid1_last[tuple(cell_index1)] = 1
for neighbhor_index in neighbhour_indices:
    grid1_last[tuple(neighbhor_index)] = -1
print("grid1_last\n", grid1_last)

neighbours:  [[1 1 1]
 [1 1 1]
 [1 1 1]]
grid1
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
cell_index
 [1 1 1]
neighbhour_indices
 [[2 1 1]
 [1 2 1]
 [1 1 2]]
grid1_last
 [[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  1. -1.]
  [ 0. -1.  0.]]

 [[ 0.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  0.]]]


In [19]:
[side_size] * dimensions

[3, 3, 3]

In [124]:
print(len(grid1.shape))

2


Create the neighborhood indices mask:

Test run: