# Input data

Init data (x, y):

In [1]:
import numpy as np
x = np.array([[0, 33, 66], [1, 300, 80], [0, 600, 550], [0, 200, 150], [0.5, 50, 300], [0.2, 128, 256], [0, 33, 66], [1, 300, 80], [0, 600, 550], [0, 200, 150], [0.5, 50, 300], [0.2, 128, 256]])
y = np.array([[9], [11], [12], [4], [8], [3], [9], [11], [12], [4], [8], [3]])
# y = y.flatten()
print("x(len: {}): {}\ny(len: {}): {}". format(x.shape[0], x, y.shape[0], y))

x(len: 12): [[0.00e+00 3.30e+01 6.60e+01]
 [1.00e+00 3.00e+02 8.00e+01]
 [0.00e+00 6.00e+02 5.50e+02]
 [0.00e+00 2.00e+02 1.50e+02]
 [5.00e-01 5.00e+01 3.00e+02]
 [2.00e-01 1.28e+02 2.56e+02]
 [0.00e+00 3.30e+01 6.60e+01]
 [1.00e+00 3.00e+02 8.00e+01]
 [0.00e+00 6.00e+02 5.50e+02]
 [0.00e+00 2.00e+02 1.50e+02]
 [5.00e-01 5.00e+01 3.00e+02]
 [2.00e-01 1.28e+02 2.56e+02]]
y(len: 12): [[ 9]
 [11]
 [12]
 [ 4]
 [ 8]
 [ 3]
 [ 9]
 [11]
 [12]
 [ 4]
 [ 8]
 [ 3]]


# Resample TS

Increase x samples per y (timesteps days IN -> 1 day out).

1 timesteps:

In [2]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

# Pad 1 element: x at the end and y at the front, due to the indexing way
x_padded = np.append(x, [[-99, -99, -99]], axis=0)
y_padded = np.insert(y, 0, -99, axis=0)

timesteps = 1
data_gen = TimeseriesGenerator(x_padded, y_padded, length=timesteps, sampling_rate=1, batch_size=x_padded.shape[0])
for i in range(len(data_gen)):
    x2, y2 = data_gen[i]
    print("{}\tx(len: {}): {}\ny(len: {}): {}". format(i, x2.shape[0], x2, y2.shape[0], y2))

0	x(len: 12): [[[0.00e+00 3.30e+01 6.60e+01]]

 [[1.00e+00 3.00e+02 8.00e+01]]

 [[0.00e+00 6.00e+02 5.50e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]]

 [[2.00e-01 1.28e+02 2.56e+02]]

 [[0.00e+00 3.30e+01 6.60e+01]]

 [[1.00e+00 3.00e+02 8.00e+01]]

 [[0.00e+00 6.00e+02 5.50e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]]

 [[2.00e-01 1.28e+02 2.56e+02]]]
y(len: 12): [[ 9]
 [11]
 [12]
 [ 4]
 [ 8]
 [ 3]
 [ 9]
 [11]
 [12]
 [ 4]
 [ 8]
 [ 3]]


2 timesteps:

In [3]:
timesteps = 2
data_gen = TimeseriesGenerator(x_padded, y_padded, length=timesteps, sampling_rate=1, batch_size=x_padded.shape[0])
for i in range(len(data_gen)):
    x2, y2 = data_gen[i]
    print("{}\tx(len: {}): {}\ny(len: {}): {}". format(i, x2.shape[0], x2, y2.shape[0], y2))

0	x(len: 11): [[[0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]]

 [[1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]]

 [[0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]]

 [[2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]]

 [[0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]]

 [[1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]]

 [[0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]]]
y(len: 11): [[11]
 [12]
 [ 4]
 [ 8]
 [ 3]
 [ 9]
 [11]
 [12]
 [ 4]
 [ 8]
 [ 3]]


3 timesteps:

In [4]:
timesteps = 3
data_gen = TimeseriesGenerator(x_padded, y_padded, length=timesteps, sampling_rate=1, batch_size=x_padded.shape[0])
for i in range(len(data_gen)):
    x2, y2 = data_gen[i]
    print("{}\tx(len: {}): {}\ny(len: {}): {}". format(i, x2.shape[0], x2, y2.shape[0], y2))

0	x(len: 10): [[[0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]]

 [[1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]]

 [[0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]]

 [[2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]]

 [[0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]]

 [[1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]]

 [[0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]]]
y(len: 10): [[12]
 [ 4]
 [ 8]
 [ 3]


7 timesteps:

In [5]:
timesteps = 7
data_gen = TimeseriesGenerator(x_padded, y_padded, length=timesteps, sampling_rate=1, batch_size=x_padded.shape[0])
for i in range(len(data_gen)):
    x2, y2 = data_gen[i]
    print("{}\tx(len: {}): {}\ny(len: {}): {}". format(i, x2.shape[0], x2, y2.shape[0], y2))

0	x(len: 6): [[[0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]]

 [[1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]]

 [[0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]]

 [[0.00e+00 2.00e+02 1.50e+02]
  [5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+02 8.00e+01]
  [0.00e+00 6.00e+02 5.50e+02]
  [0.00e+00 2.00e+02 1.50e+02]]

 [[5.00e-01 5.00e+01 3.00e+02]
  [2.00e-01 1.28e+02 2.56e+02]
  [0.00e+00 3.30e+01 6.60e+01]
  [1.00e+00 3.00e+

# DATA + "Exotic" architectures

Random regression data:

In [6]:
samples = 12
data_dim = 3
x = np.random.rand(samples, data_dim)
y = np.random.randn(samples, 1)
print("x(len: {}): {}\ny(len: {}): {}". format(x.shape[0], x, y.shape[0], y))

x(len: 12): [[7.14222111e-01 6.09997745e-01 1.96637195e-01]
 [3.01348769e-01 6.78454842e-01 9.10305949e-01]
 [3.39971918e-01 4.45906573e-01 2.01508746e-02]
 [6.01157924e-01 5.54690559e-01 4.62490382e-01]
 [8.97473524e-01 8.32346096e-01 2.60240078e-01]
 [6.50355513e-01 3.71860285e-01 8.46905502e-04]
 [2.41678029e-02 7.65766368e-01 6.72067613e-01]
 [1.59190079e-02 4.96290537e-02 7.00332315e-01]
 [8.06970754e-01 6.25818735e-01 6.79077456e-01]
 [4.19031238e-01 8.15975520e-01 7.27867227e-01]
 [7.18026640e-01 3.49038181e-01 5.60543050e-02]
 [6.76528838e-01 1.65153913e-01 6.83888533e-01]]
y(len: 12): [[ 0.5493217 ]
 [ 0.58415331]
 [ 0.26774175]
 [-0.73125187]
 [ 0.6334728 ]
 [ 0.90411759]
 [-1.02174681]
 [ 0.81673607]
 [ 0.05498526]
 [-0.66419347]
 [ 0.97059955]
 [-0.37935441]]


Data to ts:

In [7]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

# Pad 1 element: x at the end and y at the front, due to the indexing way
x_padded = np.append(x, [[-99, -99, -99]], axis=0)
y_padded = np.insert(y, 0, -99, axis=0)

timesteps = 7
data_gen = TimeseriesGenerator(x_padded, y_padded, length=timesteps, sampling_rate=1, batch_size=x_padded.shape[0])
for i in range(len(data_gen)):
    x2, y2 = data_gen[i]
    print("{}\tx(len: {}): {}\ny(len: {}): {}". format(i, x2.shape[0], x2, y2.shape[0], y2))

0	x(len: 6): [[[7.14222111e-01 6.09997745e-01 1.96637195e-01]
  [3.01348769e-01 6.78454842e-01 9.10305949e-01]
  [3.39971918e-01 4.45906573e-01 2.01508746e-02]
  [6.01157924e-01 5.54690559e-01 4.62490382e-01]
  [8.97473524e-01 8.32346096e-01 2.60240078e-01]
  [6.50355513e-01 3.71860285e-01 8.46905502e-04]
  [2.41678029e-02 7.65766368e-01 6.72067613e-01]]

 [[3.01348769e-01 6.78454842e-01 9.10305949e-01]
  [3.39971918e-01 4.45906573e-01 2.01508746e-02]
  [6.01157924e-01 5.54690559e-01 4.62490382e-01]
  [8.97473524e-01 8.32346096e-01 2.60240078e-01]
  [6.50355513e-01 3.71860285e-01 8.46905502e-04]
  [2.41678029e-02 7.65766368e-01 6.72067613e-01]
  [1.59190079e-02 4.96290537e-02 7.00332315e-01]]

 [[3.39971918e-01 4.45906573e-01 2.01508746e-02]
  [6.01157924e-01 5.54690559e-01 4.62490382e-01]
  [8.97473524e-01 8.32346096e-01 2.60240078e-01]
  [6.50355513e-01 3.71860285e-01 8.46905502e-04]
  [2.41678029e-02 7.65766368e-01 6.72067613e-01]
  [1.59190079e-02 4.96290537e-02 7.00332315e-01]
  [

In [ ]:
x_train

Train/Evaluate model:

In [29]:
from tensorflow.keras.layers import MaxPooling1D, Dropout, GlobalAveragePooling1D
from tensorflow.keras.layers import Conv1D, Reshape
data_dim = 16
timesteps = 8 #8
num_classes = 10
epochs = 5
x_train = np.random.random((10, timesteps, data_dim))
y_train = np.random.random((10, num_classes))
x_val = np.random.random((10, timesteps, data_dim))
y_val = np.random.random((10, num_classes))
x_test = np.random.random((10, timesteps, data_dim))
y_test = np.random.random((10, num_classes))

model = Sequential()
model.add(Conv1D(64, 2, activation='relu'))
model.add(Conv1D(64, 2, activation='relu'))
model.add(MaxPooling1D(2))

model.add(LSTM(16, return_sequences=True))

# model.add(Conv1D(timesteps, 2, activation='relu'))
model.add(LSTM(32))
model.add(Dense(10, activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='nadam', metrics=['accuracy'])
model.fit(x_train, y_train, verbose=1, batch_size=64, epochs=epochs, validation_data=(x_val, y_val))
score = model.evaluate(x_test, y_test, batch_size=16)
print(score)

Train on 10 samples, validate on 10 samples
Epoch 1/5
10/10 [==============================] - 1s 115ms/sample - loss: 0.2189 - acc: 0.1000 - val_loss: 0.2113 - val_acc: 0.0000e+00
Epoch 2/5
10/10 [==============================] - 0s 2ms/sample - loss: 0.2186 - acc: 0.2000 - val_loss: 0.2113 - val_acc: 0.0000e+00
Epoch 3/5
10/10 [==============================] - 0s 3ms/sample - loss: 0.2183 - acc: 0.2000 - val_loss: 0.2113 - val_acc: 0.0000e+00
Epoch 4/5
10/10 [==============================] - 0s 2ms/sample - loss: 0.2181 - acc: 0.2000 - val_loss: 0.2113 - val_acc: 0.0000e+00
Epoch 5/5
10/10 [==============================] - 0s 599us/sample - loss: 0.2457 - acc: 0.0000e+00
[0.24565787613391876, 0.0]
